/**
 * Locale mirror generator for the client bundle.
 *
 * The browser bundle cannot read `locale/*.json`, so the dictionaries have to be
 * *inside* `lib/client.js`. Rather than maintain two hand-edited copies of 170
 * keys, the JSON pair stays the single source of truth (ICD §8.5) and this script
 * derives `client/src/chrome/locale.gen.js` from it:
 *
 *     node client/src/chrome/gen-locale.mjs           # write the mirror
 *     node client/src/chrome/gen-locale.mjs --check    # exit 1 when stale
 *
 * `test/client/chrome.test.mjs` re-renders the mirror in-process and compares it
 * byte for byte, so an edited JSON without a regeneration fails the suite instead
 * of shipping a stale UI string.
 *
 * This file is a `.mjs` on purpose: the assembler only collects `client/src/**\/*.js`,
 * so the generator itself never ends up in the bundle.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
export const ROOT = resolve(HERE, '..', '..', '..')
export const ZH_FILE = join(ROOT, 'locale', 'zh.json')
export const EN_FILE = join(ROOT, 'locale', 'en.json')
export const OUT_FILE = join(HERE, 'locale.gen.js')

/** Locales the bundle ships. Order is the display order of any locale switch. */
export const LOCALES = ['zh', 'en']

/** Read the JSON pair. Throws with the offending path when a file is unusable. */
export function readLocales() {
  const dict = {}
  for (const locale of LOCALES) {
    const file = locale === 'zh' ? ZH_FILE : EN_FILE
    let raw
    try {
      raw = readFileSync(file, 'utf8')
    } catch (error) {
      throw new Error(`cannot read ${relative(ROOT, file)}: ${error.message}`)
    }
    let parsed
    try {
      parsed = JSON.parse(raw)
    } catch (error) {
      throw new Error(`${relative(ROOT, file)} is not valid JSON: ${error.message}`)
    }
    if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
      throw new Error(`${relative(ROOT, file)} must be a flat object of key → string`)
    }
    for (const [key, value] of Object.entries(parsed)) {
      if (typeof value !== 'string' || value === '') {
        throw new Error(`${relative(ROOT, file)}: "${key}" must be a non-empty string`)
      }
    }
    dict[locale] = sortKeys(parsed)
  }

  // The ICD requires the two locales to be one-to-one; catching it here means a
  // translation gap can never reach a release build.
  const reference = Object.keys(dict.zh)
  const other = new Set(Object.keys(dict.en))
  const missingEn = reference.filter((key) => !other.has(key))
  const missingZh = Object.keys(dict.en).filter((key) => !Object.prototype.hasOwnProperty.call(dict.zh, key))
  if (missingEn.length > 0 || missingZh.length > 0) {
    throw new Error(
      `locale key sets differ — missing in en: [${missingEn.join(', ')}]; missing in zh: [${missingZh.join(', ')}]`,
    )
  }
  return dict
}

/** Stable key order keeps the generated file byte-identical across runs. */
export function sortKeys(dict) {
  const out = {}
  for (const key of Object.keys(dict).sort()) out[key] = dict[key]
  return out
}

/** Render the bundled mirror for a dictionary pair. Deterministic. */
export function render(dict) {
  const entries = Object.entries(dict)
    .map(([locale, table]) => `  const ${locale} = ${indent(JSON.stringify(table, null, 2), 2)}`)
    .join('\n\n')
  const names = Object.keys(dict)
    .map((locale) => `${locale}`)
    .join(', ')
  return `/**
 * @module ssh.i18n.dict
 * @order 58
 *
 * GENERATED by client/src/chrome/gen-locale.mjs — do not edit by hand.
 * Source of truth: locale/zh.json + locale/en.json (ICD §8.5). The browser bundle
 * cannot fetch those files, so the dictionaries are compiled in; regenerate with
 *
 *     node client/src/chrome/gen-locale.mjs
 *
 * and let test/client/chrome.test.mjs prove the mirror matches the JSON pair.
 */

SSH.define('ssh.i18n.dict', function () {
${entries}

  /** Every key both locales define, so a key-set regression is visible at runtime. */
  const KEYS = Object.freeze(Object.keys(zh))

  return { dictionaries: { ${names} }, KEYS }
})
`
}

function indent(text, spaces) {
  const pad = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line, index) => (index === 0 ? line : pad + line))
    .join('\n')
}

/** Current mirror content, as it should be on disk. */
export function expectedMirror() {
  return render(readLocales())
}

function runCli() {
  const expected = expectedMirror()
  const check = process.argv.includes('--check')
  if (check) {
    let current = ''
    try {
      current = readFileSync(OUT_FILE, 'utf8')
    } catch {
      console.error(`locale mirror missing: ${relative(ROOT, OUT_FILE)} (run: node client/src/chrome/gen-locale.mjs)`)
      process.exitCode = 1
      return
    }
    if (current !== expected) {
      console.error('locale mirror is stale: run `node client/src/chrome/gen-locale.mjs`')
      process.exitCode = 1
      return
    }
    console.log('locale mirror is up to date')
    return
  }
  writeFileSync(OUT_FILE, expected, 'utf8')
  const keys = Object.keys(readLocales().zh).length
  console.log(`wrote ${relative(ROOT, OUT_FILE)} (${keys} keys × ${LOCALES.length} locales)`)
}

const invokedDirectly = (() => {
  const entry = process.argv[1]
  if (!entry) return false
  try {
    return resolve(entry) === resolve(fileURLToPath(import.meta.url))
  } catch {
    return false
  }
})()

if (invokedDirectly) runCli()
