/**
 * Theme mirror generator for the client bundle.
 *
 * `client/src/theme.css` is the editable source of truth, but the browser cannot
 * fetch a stylesheet from the plugin source tree, so the CSS has to be *inside*
 * `lib/client.js`. This script compiles it into `client/src/chrome/theme.gen.js`:
 *
 *     node client/src/chrome/gen-theme.mjs           # write the mirror
 *     node client/src/chrome/gen-theme.mjs --check    # exit 1 when stale
 *
 * `test/client/chrome.test.mjs` re-renders the mirror in-process and compares it byte
 * for byte, so editing the CSS without regenerating fails the suite.
 *
 * A `.mjs` on purpose: the assembler collects `client/src/**\/*.js` only, so this
 * generator never reaches the bundle.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
export const ROOT = resolve(HERE, '..', '..', '..')
export const CSS_FILE = join(ROOT, 'client', 'src', 'theme.css')
export const OUT_FILE = join(HERE, 'theme.gen.js')

/** Read the stylesheet, normalising line endings so the mirror is platform-stable. */
export function readTheme() {
  try {
    return readFileSync(CSS_FILE, 'utf8').replace(/\r\n/g, '\n')
  } catch (error) {
    throw new Error(`cannot read client/src/theme.css: ${error.message}`)
  }
}

/** Wrap CSS in a JS template literal, escaping the three characters that matter. */
export function quoteTemplate(css) {
  const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
  return `\`${escaped}\``
}

/** Render the bundled mirror. Deterministic for a given stylesheet. */
export function render(css) {
  const body = css.replace(/\s+$/, '')
  return `/**
 * @module ssh.chrome.theme.css
 * @order 56
 *
 * GENERATED by client/src/chrome/gen-theme.mjs — do not edit by hand.
 * Source of truth: client/src/theme.css. Every colour in it is a --dsw-* token
 * (ICD §8.6), so light and dark need no second code path. Regenerate with
 *
 *     node client/src/chrome/gen-theme.mjs
 */

SSH.define('ssh.chrome.theme.css', function () {
  /** The stylesheet exactly as authored, inserted once per client run. */
  const CSS = ${quoteTemplate(body)}

  /**
   * Class name prefixes the chrome owns. Exported so tests and the shell can tell
   * plugin chrome apart from shipped UI without parsing the stylesheet.
   */
  const PREFIX = 'dsh-ssh-'

  return { CSS, PREFIX }
})
`
}

/** Current mirror content, as it should be on disk. */
export function expectedMirror() {
  return render(readTheme())
}

function runCli() {
  const expected = expectedMirror()
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(OUT_FILE, 'utf8')
    } catch {
      console.error(`theme mirror missing: ${relative(ROOT, OUT_FILE)} (run: node client/src/chrome/gen-theme.mjs)`)
      process.exitCode = 1
      return
    }
    if (current !== expected) {
      console.error('theme mirror is stale: run `node client/src/chrome/gen-theme.mjs`')
      process.exitCode = 1
      return
    }
    console.log('theme mirror is up to date')
    return
  }
  writeFileSync(OUT_FILE, expected, 'utf8')
  console.log(`wrote ${relative(ROOT, OUT_FILE)} (${readTheme().length} bytes of CSS)`)
}

const invokedDirectly = (() => {
  const entry = process.argv[1]
  if (!entry) return false
  try {
    return resolve(entry) === resolve(fileURLToPath(import.meta.url))
  } catch {
    return false
  }
})()

if (invokedDirectly) runCli()
