/**
 * @module ssh.chrome.theme.css
 * @order 56
 *
 * GENERATED by client/src/chrome/gen-theme.mjs — do not edit by hand.
 * Source of truth: client/src/theme.css. Every colour in it is a --dsw-* token
 * (ICD §8.6), so light and dark need no second code path. Regenerate with
 *
 *     node client/src/chrome/gen-theme.mjs
 */

SSH.define('ssh.chrome.theme.css', function () {
  /** The stylesheet exactly as authored, inserted once per client run. */
  const CSS = `/*
 * @local/dsh-ssh — chrome theme (ICD §8.6)
 *
 * Every colour, border and radius below references a DSH design token, so light and
 * dark follow the shell with no media query and no second code path. The only
 * literal colours allowed here are hue-free black shadows.
 *
 * This file is the source of truth for the bundled stylesheet: the browser cannot
 * fetch it, so \`node client/src/chrome/gen-theme.mjs\` compiles it into
 * \`client/src/chrome/theme.gen.js\`, and \`test/client/chrome.test.mjs\` compares the
 * mirror byte for byte. Edit this file, regenerate, never the reverse.
 */

/* ── root & typography ───────────────────────────────────────────────────── */

.dsh-ssh-root {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 0;
  color: var(--dsw-alias-label-primary);
  font: 400 12px/1.5 inherit;
}

/* The terminal face is fixed by the ICD; the size is user-adjustable. */
.dsh-ssh-term,
.dsh-ssh-mono-inline {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: var(--dsh-ssh-term-size, 13px);
  line-height: 1.45;
}

.dsh-ssh-chrome {
  display: flex;
  flex-direction: column;
  min-width: 0;
}

/* ── theme switch ────────────────────────────────────────────────────────────
   Sits in the session toolbar, outside \`.dsh-ssh-session-help\`, so the narrow-sidebar
   container query never hides it. Token-only (ICD §8.6): the icon inherits the label
   colour so it inverts with the theme, and every shadow is a \`color-mix\` of a token. */

.dsh-ssh-theme-toggle {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  flex: 0 0 auto;
  padding: 2px 8px;
  font: inherit;
  font-size: 12px;
  line-height: 1.6;
  color: var(--dsw-alias-label-primary);
  background: var(--dsw-alias-bg-layer-2, var(--dsw-alias-bg-layer-1));
  border: 1px solid var(--dsw-alias-border-l1);
  border-radius: 6px;
  cursor: pointer;
}

.dsh-ssh-theme-toggle:hover {
  border-color: var(--dsw-alias-border-l2);
  background: color-mix(in srgb, var(--dsw-alias-brand-primary) 8%, var(--dsw-alias-bg-layer-2));
}

.dsh-ssh-theme-toggle:focus-visible {
  outline: 2px solid var(--dsw-alias-brand-primary);
  outline-offset: 1px;
}

.dsh-ssh-theme-toggle-icon {
  font-size: 13px;
  color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary));
}

.dsh-ssh-theme-toggle[aria-pressed='true'] {
  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--dsw-alias-label-primary) 16%, transparent);
}

/* ── session tab strip ───────────────────────────────────────────────────── */

.dsh-ssh-tabstrip {
  display: flex;
  align-items: stretch;
  gap: 4px;
  min-width: 0;
  padding: 4px 6px;
  border-bottom: 1px solid var(--dsw-alias-border-l1);
  background: var(--dsw-alias-specific-sidebar-fill, var(--dsw-alias-bg-layer-1));
}

.dsh-ssh-tabstrip-inner {
  display: flex;
  align-items: center;
  gap: 2px;
  min-width: 0;
  overflow-x: auto;
  scrollbar-width: thin;
}

.dsh-ssh-tab {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  flex: none;
  max-width: 190px;
  padding: 1px 2px 1px 1px;
  border: 1px solid transparent;
  border-radius: 6px;
  background: transparent;
  color: var(--dsw-alias-label-secondary);
}

.dsh-ssh-tab:hover {
  background: var(--dsw-alias-bg-layer-2);
  color: var(--dsw-alias-label-primary);
}

.dsh-ssh-tab[data-active="true"] {
  background: var(--dsw-alias-bg-layer-2);
  border-color: var(--dsw-alias-border-l2);
  color: var(--dsw-alias-label-primary);
}

.dsh-ssh-tab[data-over="true"] {
  border-color: var(--dsw-alias-brand-primary);
}

/* The clickable half of a chip: the state dot plus the session label. */
.dsh-ssh-tab-main {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  min-width: 0;
  padding: 2px 2px 2px 7px;
  border: 1px solid transparent;
  border-radius: 5px;
  background: transparent;
  color: inherit;
  font: inherit;
  cursor: pointer;
}

.dsh-ssh-tab-main:focus-visible,
.dsh-ssh-tab-close:focus-visible,
.dsh-ssh-tab-tool:focus-visible,
.dsh-ssh-status-btn:focus-visible,
.dsh-ssh-toast-btn:focus-visible,
.dsh-ssh-confirm-btn:focus-visible {
  outline: 2px solid var(--dsw-alias-brand-primary);
  outline-offset: 1px;
}

.dsh-ssh-tab-label {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* State dot: the ICD fixes green / yellow / red per connection state. */
.dsh-ssh-tab-state {
  width: 7px;
  height: 7px;
  flex: none;
  border-radius: 50%;
  background: var(--dsw-alias-state-idle-primary);
}

.dsh-ssh-tab-state[data-state="connected"] {
  background: var(--dsw-alias-state-success-primary);
}

.dsh-ssh-tab-state[data-state="connecting"] {
  background: var(--dsw-alias-state-warn-primary);
}

.dsh-ssh-tab-state[data-state="error"] {
  background: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-tab-close,
.dsh-ssh-tab-tool,
.dsh-ssh-status-btn,
.dsh-ssh-toast-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 4px;
  border: 1px solid transparent;
  border-radius: 5px;
  background: transparent;
  color: inherit;
  font: inherit;
  cursor: pointer;
}

.dsh-ssh-tab-close,
.dsh-ssh-tab-tool {
  width: 18px;
  height: 18px;
  padding: 0;
  opacity: 0.72;
}

/* Intentionally empty: the class above only exists to keep the close affordance and
   the strip's own tools visually identical. */
.dsh-ssh-tab-close:hover,
.dsh-ssh-tab-tool:hover {
  background: var(--dsw-alias-bg-base);
  border-color: var(--dsw-alias-border-l1);
  opacity: 1;
}

.dsh-ssh-tabstrip-tools {
  display: flex;
  align-items: center;
  gap: 2px;
  margin-left: auto;
}

.dsh-ssh-tabstrip-empty {
  padding: 4px 8px;
  color: var(--dsw-alias-label-secondary);
  font-size: 11px;
}

/* ── status bar ──────────────────────────────────────────────────────────── */

.dsh-ssh-statusbar {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  padding: 4px 8px;
  border-top: 1px solid var(--dsw-alias-border-l1);
  background: var(--dsw-alias-bg-layer-2);
  font-size: 11px;
  color: var(--dsw-alias-label-secondary);
}

.dsh-ssh-status-item {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  white-space: nowrap;
}

.dsh-ssh-status-value {
  color: var(--dsw-alias-label-primary);
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.dsh-ssh-status-state[data-state="connected"] {
  color: var(--dsw-alias-state-success-primary);
}

.dsh-ssh-status-state[data-state="error"] {
  color: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-status-state[data-state="connecting"],
.dsh-ssh-status-state[data-state="authenticating"] {
  color: var(--dsw-alias-state-warn-primary);
}

.dsh-ssh-status-actions {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-left: auto;
}

.dsh-ssh-status-btn {
  padding: 1px 8px;
  border-color: var(--dsw-alias-border-l1);
  background: var(--dsw-alias-bg-layer-1);
  color: var(--dsw-alias-label-primary);
  font-size: 11px;
}

.dsh-ssh-status-btn:hover:not(:disabled) {
  border-color: var(--dsw-alias-brand-primary);
}

.dsh-ssh-status-btn:disabled {
  opacity: 0.55;
  cursor: default;
}

.dsh-ssh-status-progress {
  position: relative;
  width: 96px;
  height: 4px;
  border-radius: 999px;
  background: var(--dsw-alias-bg-base);
  overflow: hidden;
}

.dsh-ssh-status-progress > span {
  display: block;
  height: 100%;
  background: var(--dsw-alias-brand-primary);
}

/* ── toasts (shell.overlay is click-through — see \`.dsh-ssh-toast\`) ──────── */

.dsh-ssh-toasts {
  position: fixed;
  right: 16px;
  bottom: 16px;
  z-index: 2147483000;
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: min(380px, calc(100vw - 32px));
  max-height: 70vh;
  overflow: auto;
  /* The overlay layer underneath passes clicks through, so the stack itself must
     not swallow them either — only its cards opt in. */
  pointer-events: none;
}

.dsh-ssh-toast {
  /* Mandatory: without this the buttons inside a shell.overlay occupant are inert
     (M0-SPIKE §4 C4). */
  pointer-events: auto;
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 8px 10px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-left-width: 3px;
  border-radius: 8px;
  background: var(--dsw-alias-bg-overlay);
  color: var(--dsw-alias-label-primary);
  box-shadow: 0 8px 24px color-mix(in srgb, var(--dsw-alias-label-primary) 16%, transparent);
}

.dsh-ssh-toast[data-kind="success"] {
  border-left-color: var(--dsw-alias-state-success-primary);
}

.dsh-ssh-toast[data-kind="info"] {
  border-left-color: var(--dsw-alias-brand-primary);
}

.dsh-ssh-toast[data-kind="warn"] {
  border-left-color: var(--dsw-alias-state-warn-primary);
}

.dsh-ssh-toast[data-kind="error"] {
  border-left-color: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-toast-body {
  flex: 1 1 auto;
  min-width: 0;
}

.dsh-ssh-toast-text {
  word-break: break-word;
}

.dsh-ssh-toast-detail {
  margin-top: 4px;
  padding: 6px 8px;
  border-radius: 6px;
  background: var(--dsw-alias-bg-base);
  color: var(--dsw-alias-label-secondary);
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 11px;
  white-space: pre-wrap;
  word-break: break-all;
  max-height: 160px;
  overflow: auto;
}

.dsh-ssh-toast-actions {
  display: flex;
  align-items: center;
  gap: 4px;
  flex: none;
}

.dsh-ssh-toast-btn {
  padding: 2px 6px;
  border-color: var(--dsw-alias-border-l1);
  font-size: 11px;
}

.dsh-ssh-toast-btn:hover {
  border-color: var(--dsw-alias-brand-primary);
}

/* ── confirmation dialog (dangerous operations) ──────────────────────────── */

.dsh-ssh-confirm-backdrop {
  position: fixed;
  inset: 0;
  z-index: 2147483100;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  background: var(--dsw-alias-bg-overlay);
  /* An occupant of a click-through layer must claim its own pointer events. */
  pointer-events: auto;
}

.dsh-ssh-confirm {
  width: min(420px, 100%);
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 14px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 10px;
  background: var(--dsw-alias-bg-layer-1);
  color: var(--dsw-alias-label-primary);
  box-shadow: 0 16px 40px color-mix(in srgb, var(--dsw-alias-label-primary) 22%, transparent);
}

.dsh-ssh-confirm[data-danger="true"] {
  border-color: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-confirm-title {
  font-weight: 600;
  font-size: 13px;
}

.dsh-ssh-confirm[data-danger="true"] .dsh-ssh-confirm-title {
  color: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-confirm-body {
  color: var(--dsw-alias-label-secondary);
  word-break: break-word;
}

.dsh-ssh-confirm-type {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.dsh-ssh-confirm-hint {
  font-size: 11px;
  color: var(--dsw-alias-label-secondary);
}

.dsh-ssh-input {
  width: 100%;
  box-sizing: border-box;
  padding: 5px 8px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 6px;
  background: var(--dsw-alias-bg-base);
  color: var(--dsw-alias-label-primary);
  font: inherit;
}

.dsh-ssh-input:focus-visible {
  outline: none;
  border-color: var(--dsw-alias-brand-primary);
}

.dsh-ssh-input[data-invalid="true"] {
  border-color: var(--dsw-alias-state-error-primary);
}

.dsh-ssh-confirm-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}

.dsh-ssh-confirm-btn {
  padding: 4px 12px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 6px;
  background: var(--dsw-alias-bg-layer-2);
  color: var(--dsw-alias-label-primary);
  font: inherit;
  cursor: pointer;
}

.dsh-ssh-confirm-btn:hover:not(:disabled) {
  border-color: var(--dsw-alias-brand-primary);
}

.dsh-ssh-confirm-btn:disabled {
  opacity: 0.5;
  cursor: default;
}

.dsh-ssh-confirm-btn[data-kind="primary"] {
  background: var(--dsw-alias-brand-primary);
  border-color: var(--dsw-alias-brand-primary);
  color: var(--dsw-alias-bg-base);
}

.dsh-ssh-confirm-btn[data-kind="danger"] {
  background: var(--dsw-alias-state-error-primary);
  border-color: var(--dsw-alias-state-error-primary);
  color: var(--dsw-alias-bg-base);
}

/* ── shortcut reference ─────────────────────────────────────────────────── */

.dsh-ssh-shortcuts-backdrop {
  position: fixed;
  inset: 0;
  z-index: 2147483100;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  background: var(--dsw-alias-bg-overlay);
  pointer-events: auto;
}

.dsh-ssh-shortcuts {
  width: min(520px, 100%);
  max-height: 80vh;
  overflow: auto;
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 14px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 10px;
  background: var(--dsw-alias-bg-layer-1);
  color: var(--dsw-alias-label-primary);
  box-shadow: 0 16px 40px color-mix(in srgb, var(--dsw-alias-label-primary) 20%, transparent);
}

.dsh-ssh-shortcuts-head {
  display: flex;
  align-items: center;
  gap: 8px;
}

.dsh-ssh-shortcuts-title {
  font-weight: 600;
  font-size: 13px;
}

.dsh-ssh-shortcuts-note {
  color: var(--dsw-alias-label-secondary);
  font-size: 11px;
}

.dsh-ssh-shortcuts-group {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.dsh-ssh-shortcuts-group-title {
  color: var(--dsw-alias-label-secondary);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.dsh-ssh-shortcuts-row {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 4px 12px;
  align-items: baseline;
  padding: 3px 0;
  border-bottom: 1px solid var(--dsw-alias-border-l1);
}

.dsh-ssh-shortcuts-row[data-source="conflict"] {
  color: var(--dsw-alias-state-warn-primary);
}

.dsh-ssh-shortcuts-label {
  word-break: break-word;
}

.dsh-ssh-shortcuts-keys {
  display: inline-flex;
  align-items: center;
  gap: 3px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.dsh-ssh-shortcuts-key {
  padding: 0 5px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 4px;
  background: var(--dsw-alias-bg-layer-2);
  color: var(--dsw-alias-label-primary);
  font-size: 11px;
}

.dsh-ssh-shortcuts-source {
  font-size: 10px;
  color: var(--dsw-alias-label-secondary);
}

.dsh-ssh-shortcuts-empty {
  color: var(--dsw-alias-label-secondary);
}`

  /**
   * Class name prefixes the chrome owns. Exported so tests and the shell can tell
   * plugin chrome apart from shipped UI without parsing the stylesheet.
   */
  const PREFIX = 'dsh-ssh-'

  return { CSS, PREFIX }
})
