/**
 * The client assembler is build infrastructure, so it gets its own tests.
 *
 * A bundler that is *almost* right fails in the browser, where the symptom is a
 * blank panel and the cause is invisible. The properties asserted here are the
 * ones the ICD relies on: determinism, one loader row, a rejected malformed
 * source, and a committed artifact that matches its sources.
 */

import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { test } from 'node:test'

import { assertParsableBundle, assertUniqueModules, buildBundle, collectSources, OUT_FILE, parseSource, ROOT } from '../../scripts/build-client.mjs'

test('assembly is deterministic: the same sources produce identical bytes', () => {
  const first = buildBundle()
  const second = buildBundle()
  assert.equal(first, second)
})

test('a source corrupted by an encoding round trip fails the build, with the line named', () => {
  // This is the failure that shipped a blank panel once: a UTF-8 file edited
  // through a PowerShell pipeline lost its non-ASCII characters to U+FFFD, the
  // assembler accepted it, and the browser could not parse the bundle.
  const corrupted = '// @module ssh.bad\n// @order 10\nSSH.define("ssh.bad", function () { return "\uFFFD" })\n'
  assert.throws(
    () => parseSource(join(ROOT, 'client', 'src', 'bad.js'), corrupted),
    /U\+FFFD replacement character/,
  )
  // The message must name the file and the line, or it is not actionable.
  try {
    parseSource(join(ROOT, 'client', 'src', 'bad.js'), corrupted)
    assert.fail('expected a throw')
  } catch (error) {
    assert.match(error.message, /client[\\/]src[\\/]bad\.js:3/)
  }
})

test('a bundle that cannot be parsed is rejected instead of written', () => {
  assert.throws(() => assertParsableBundle('window.__ModuleLoader__.load({ id: "x", factory: (require) => {'), /not parsable/)
  // A well-formed bundle must pass: the guard cannot be so strict that it blocks
  // legitimate output.
  assert.doesNotThrow(() => assertParsableBundle(buildBundle()))
})

test('the committed bundle matches its sources', () => {
  // This is the guarantee `--check` enforces in CI; asserting it here means a
  // forgotten rebuild fails the unit suite too.
  const onDisk = readFileSync(OUT_FILE, 'utf8')
  assert.equal(onDisk, buildBundle(), 'run `node scripts/build-client.mjs` and commit lib/client.js')
})

test('the bundle registers exactly one DSH package row under the right id', () => {
  const bundle = buildBundle()
  const loads = bundle.match(/window\.__ModuleLoader__\.load\(/g) ?? []
  assert.equal(loads.length, 1)
  assert.match(bundle, /id: "@local\/dsh-ssh"/)
  assert.match(bundle, /factory: \(require\) => \{/)
  assert.match(bundle, /^\/\/ GENERATED by scripts\/build-client\.mjs/m)
})

test('the bundle requests react and declares no other external', () => {
  const bundle = buildBundle()
  // Only bare `require(...)` counts: `SSH.require('ssh.core')` is the in-bundle
  // module registry and must not be mistaken for an external request.
  const requires = [...bundle.matchAll(/(?<![\w.])require\((["'])([^"']+)\1\)/g)].map((m) => m[2])
  assert.deepEqual([...new Set(requires)], ['react'])
})

test('every source declares a namespace-prefixed module name', () => {
  const sources = collectSources().map((file) => parseSource(file))
  assert.ok(sources.length >= 5, 'the client half ships several modules')
  for (const source of sources) {
    assert.match(source.moduleName, /^ssh\.[a-z][a-z0-9.]*$/, `${source.moduleName} follows the ssh.* namespace`)
  }
  // Emitted in ascending @order, which is the only ordering contract authors own.
  const sorted = [...sources].sort((a, b) => a.order - b.order)
  assert.deepEqual(sources.map((s) => s.moduleName).sort(), sorted.map((s) => s.moduleName).sort())
})

test('a source without a module header is rejected', () => {
  assert.throws(
    () => parseSource(join(ROOT, 'client', 'src', 'fake.js'), 'SSH.define("ssh.fake", function () {})'),
    /missing "@module <name>" header/,
  )
})

test('a source without SSH.define is rejected', () => {
  assert.throws(
    () => parseSource(join(ROOT, 'client', 'src', 'fake.js'), '// @module ssh.fake\nvar x = 1'),
    /must call SSH\.define/,
  )
})

test('ESM syntax in a client source is rejected, with the fix in the message', () => {
  assert.throws(
    () => parseSource(join(ROOT, 'client', 'src', 'fake.js'), '// @module ssh.fake\nimport x from "y"\nSSH.define("ssh.fake", function () {})'),
    /ESM syntax is not allowed/,
  )
})

test('an out-of-range @order is rejected', () => {
  assert.throws(
    () => parseSource(join(ROOT, 'client', 'src', 'fake.js'), '// @module ssh.fake\n// @order 1000\nSSH.define("ssh.fake", function () {})'),
    /@order/,
  )
})

test('two files claiming one module name fail the build', () => {
  const sources = [
    { moduleName: 'ssh.dup', file: join(ROOT, 'client', 'src', 'a.js') },
    { moduleName: 'ssh.dup', file: join(ROOT, 'client', 'src', 'b.js') },
  ]
  assert.throws(() => assertUniqueModules(sources), /duplicate @module "ssh\.dup"/)
})

test('the client source tree contains no hardcoded colours', () => {
  // The ICD requires every colour to come from a --dsw-* token so light and dark
  // need no second code path. Shadows are included (ICD v1.0.8 removed the earlier
  // "neutral alpha" exception): a black-alpha shadow is invisible on a dark
  // background, so it is a theme-fidelity defect rather than a style preference.
  // Derive shadows instead, e.g.
  //   box-shadow: 0 12px 32px color-mix(in srgb, var(--dsw-alias-label-primary) 18%, transparent);
  //
  // `client/src/vendor/**` is excluded by decision (ICD §8.6): vendored third-party
  // code keeps its own default theme, and we override it with tokens at runtime.
  // Auditing upstream's palette would only force us to fork it.
  const offenders = []
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (entry.name === 'vendor') continue
        walk(join(dir, entry.name))
      } else if (entry.name.endsWith('.js')) {
        const full = join(dir, entry.name)
        const text = readFileSync(full, 'utf8')
        const matches = text.match(/#[0-9a-fA-F]{3,8}\b|rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+[^)]*\)/g) ?? []
        for (const match of matches) {
          offenders.push(`${entry.name}: ${match}`)
        }
      }
    }
  }
  walk(join(ROOT, 'client', 'src'))
  assert.deepEqual(offenders, [])
})
